### ISSUE TITLE
ym2017 refuses to build

### ISSUE THREAD

**Issue by jason-oliveira** [andwn/ym2017#3]
Full output of make:
https://pastebin.com/raw/AhcbjVpP

## Expected Result:

ym2017 builds and links.

## Actual Result:

ld barfs

**Comment by cyberic99** [comment]
I think you should add ``-fcommon`` to the ``CCFLAGS`` (see https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common)

**Comment by andwn** [comment]
The ld errors are because of the no-common thing but I think it's going to take more than -fcommon and rescomp.jar to make it run properly again. The toolchains and SGDK tools have had several breaking changes over the past 4 years. Rescomp in particular has changed the structs it outputs so palettes/tilesets can get corrupted and crash. The XGM driver code may need to be updated too. Another thing on my TODO list I guess.

**Comment by andwn** [comment]
Eh screw it I'll do it now, got a half hour to kill.

**Comment by jason-oliveira** [comment]
It worked great, outside of the corrupted tilesets in the binary that @andwn mentioned. At least the music plays now!  

is -fcommon a gentoo-only thing, or is this now standard for every distro?

**Comment by andwn** [comment]
It's an upstream change to GCC 10.x that affects everyone. I updated marsdev to use 10.3 last week and haven't gotten to adding -fcommon everywhere yet.

**Comment by andwn** [comment]
The default is supposed to improve LTO output, so I'll probably start putting extern in all my header variables to avoid needing -fcommon eventually

**Comment by andwn** [comment]
Ok that should do it. There were 3 more problems: 1. Palette struct "index" field had to be removed. 2. Outdated LZ4W decompression algorithm outputting garbage. 3. Had to add new optimization field for TILESET as 0 (none)

**Comment by jason-oliveira** [comment]
Working perfectly in BlastEm now. Thanks a bunch.
